### ISSUE TITLE
vhost of phpmyadmin not created

### ISSUE THREAD

**Issue by sasselin** [iJoyCode/vagrant-puppet-centos-php-apache#1]
Does the vhost phpmyadmin installs correctly on your side? I used your repositories as a base but phpmyadmin is not installed correctly. The vhost is not created. If you find the problem, please commit, I'm interested.

I still look to my side.

Thank you for your job! It's a nice setup of Vagrant I need.

**Comment by Fortitude20** [comment]
same issue, phpMyAdmin is install but I can't access it. Also can't find the conf file at /etc/httpd/conf.d/phpMyAdmin.conf

**Comment by iJoyCode** [comment]
Today I've added fully new solution for latest version of vagrant. This problem isn't actual.
For using PhpMyAdmin just copy folder to your "/www" synced folder and use http://192.168.33.10/phpmyadmin/
